server:
  port: 9020
spring:
  application:
    name: sample-microservice-A
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
