server:
  port: 9050
spring:
  application:
    name: sample-microservice-B
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

